<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXRSJYxm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXRSJYxm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXRSJYxm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXRSJYxm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXRSJYxm\App_KernelDevDebugContainer([
    'container.build_hash' => 'XRSJYxm',
    'container.build_id' => 'b97407ec',
    'container.build_time' => 1610891298,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXRSJYxm');
